import { ArrowUpRight, ArrowDown, Trophy, Users, Flag, Heart, Shield } from 'lucide-react';

export default function Home() {
  return <>
    <header className="header"><a className="brand" href="#" aria-label="Fantacalcio da Sikinenz, home"><span className="brand-icon"><Shield size={23}/></span><span>FANTACALCIO<br/><b>DA SIKINENZ</b></span></a><nav aria-label="Navigazione principale"><a href="#lega">La lega</a><a href="#partecipanti">I partecipanti</a><a href="#montepremi">Montepremi <ArrowUpRight size={14}/></a></nav><span className="est">EST. 2026</span></header>
    <main>
      <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span/> OTTO RIVALI. UNA SOLA LEGA.</p><h1 id="hero-title">IL CALCIO È<br/>UNA FEDE.<br/><em>IL FANTA,<br/>UNA GUERRA.</em></h1><p className="intro">Benvenuti al Fantacalcio da Sikinenz.<br/>Amici fuori dal campo. Avversari fino all’ultimo bonus.</p><a className="cta" href="#lega">Entra nello spirito della lega <ArrowUpRight size={19}/></a></div><div className="hero-art"><div className="art-caption"><span>PASSIONE, RIVALITÀ, GLORIA.</span><span>DAL 2026</span></div><img className="crest" src="/logo.png" alt="Stemma Fantacalcio da Sikinenz: ritratto con maglia rossonera, corona e alloro dorato"/><p className="art-bottom">IL NOSTRO NOME. <b>LA NOSTRA STORIA.</b></p></div><a href="#lega" className="scroll"><ArrowDown size={14}/> SCOPRI LA LEGA</a></section>
      <section className="stats" aria-label="La lega in numeri"><div><Users/><strong>08</strong><span>PARTECIPANTI<br/><small>Otto modi di sognare il titolo.</small></span></div><div><Trophy/><strong>400<span>€</span></strong><span>MONTEPREMI TOTALE<br/><small>La gloria ha anche un prezzo.</small></span></div><div><Flag/><strong>2026</strong><span>L’ANNO ZERO<br/><small>Le grandi rivalità iniziano qui.</small></span></div></section>
      <section className="about section" id="lega"><div><p className="eyebrow">01 — LA NOSTRA LEGA</p><h2>CI DIVIDE LA FORMAZIONE.<br/><em>CI UNISCE LA PASSIONE.</em></h2></div><div className="about-copy"><p>Una lega, otto partecipanti e quella voglia di vincere che rende speciale ogni giornata.</p><p>Fantacalcio da Sikinenz è il nostro appuntamento con il calcio: intuizioni da allenatore, gol all’ultimo minuto e sfottò che durano tutta la settimana. Perché il bello del fanta è giocarsela insieme.</p><span className="signature"><Heart size={16}/> CUORE ROSSONERO. SPIRITO COMPETITIVO.</span></div></section>
      <section className="players section" id="partecipanti"><div className="section-head"><div><p className="eyebrow">02 — I PROTAGONISTI</p><h2>OTTO POSTI.<br/><em>UNA SOLA AMBIZIONE.</em></h2></div><p>La sfida è tra otto partecipanti.<br/>I nomi dei protagonisti saranno annunciati qui.</p></div><div className="player-grid">{Array.from({length:8},(_,i)=><article className="player" key={i}><span className="player-index">{String(i+1).padStart(2,'0')}</span><Shield size={31} strokeWidth={1}/><h3>Partecipante {String(i+1).padStart(2,'0')}</h3><p>Nome da annunciare</p></article>)}</div></section>
      <section className="prize section" id="montepremi"><div><p className="eyebrow">03 — LA POSTA IN GIOCO</p><h2>PER LA GLORIA.<br/><em>E NON SOLO.</em></h2><p>Ogni scelta conta. Ogni bonus pesa.<br/>In palio, il montepremi della nostra lega.</p><span className="prize-note">La ripartizione dei premi sarà comunicata prossimamente.</span></div><div className="prize-value"><Trophy size={38} strokeWidth={1.3}/><strong>400<span>€</span></strong><span>MONTEPREMI TOTALE</span></div></section>
      <section className="closing"><p>FANTACALCIO DA SIKINENZ</p><h2>CHE VINCA <em>IL MIGLIORE.</em><br/><span>O QUELLO CON PIÙ CULO.</span></h2><a href="#">Torna in cima <ArrowUpRight size={16}/></a></section>
    </main><footer><a className="brand" href="#"><Shield size={22}/><span>FANTACALCIO DA SIKINENZ</span></a><p>8 partecipanti. 400 € in palio. Infinite discussioni.</p><span>© 2026 · Fatto per la nostra lega.</span></footer>
  </>;
}
